[package]
name = "concord"
version = "0.1.0"
authors = ["Dino Wernli <dinowernli@gmail.com>"]
edition = "2018"

[dependencies]
grpc = "0.8"
protobuf = "2.15.0"
grpc-protobuf = "0.8"

[build-dependencies]
protoc-rust-grpc = "0.8"
