[package]
name = "concord"
version = "0.1.0"
authors = ["Dino Wernli <dinowernli@gmail.com>"]
edition = "2018"

[dependencies]
async-std = {version = "1.9.0", features = ["attributes"]}
async-trait = "0.1.51"
bytes = "0.5.6"
chrono = "0.4.19"
env_logger = "0.9.0"
futures = "0.3.5"
im = "15.0.0"
libmath = "0.2.1"
log = "0.4.14"
prost = "0.8"
rand = "0.7.3"
structopt = "0.3.25"
timer = "0.2.0"
tokio = { version = "1.12", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.7", features = ["net"] }
tonic = "0.5"

[build-dependencies]
tonic-build = "0.5"
